FROM python:3.12-slim AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
WORKDIR /app
COPY pyproject.toml README.md ./
COPY {{ package_name }} ./{{ package_name }}
RUN uv build --wheel --out-dir dist

FROM python:3.12-slim AS runtime
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
COPY uv.lock pyproject.toml ./
COPY --from=builder /app/dist /app/dist
RUN uv pip install --system --constraint uv.lock /app/dist/*.whl && rm -rf /app/dist
