name: Template Docker build

on:
  - push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install copier
        run: uv tool install copier

      - name: Generate project
        run: >
          copier copy --defaults
          --data project_name=test-project
          . /tmp/test-project

      - name: Generate lock file
        run: uv lock --project /tmp/test-project

      - name: Set up Docker runtime
        uses: docker/setup-buildx-action@v3

      - name: Build generated image
        uses: docker/build-push-action@v6
        with:
          context: /tmp/test-project
          load: true
          push: false
          tags: local/generated-test-image:latest

      - name: Run generated image help
        run: docker run --rm --entrypoint test-project local/generated-test-image:latest --help
